---
title: "Pre-Analysis Plan Version 1"
author: "HEGSRR"
date: "`r Sys.Date()`"
output: html_document
editor_options:
  markdown:
    wrap: sentence
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../docs") })
nocite: '@*'
bibliography: "../../software.bib"
---

# Abstract

This study is a *reproduction* of: Tuholske, C., Lynch, V.D., Spriggs, R.
et al.
Hazardous heat exposure among incarcerated people in the United States.
Nat Sustain 7, 394–398 (2024).
<https://doi.org/10.1038/s41893-024-01293-y> [Git Repository](https://github.com/sparklabnyc/temperature_prisons_united_states_2024)

By reproducing the exploratory data analysis done in Tuholske et al. (2024), we seek to...
*1.* Identify the temporal resolution at which authors use population data to calculate population weighted hazardous heat days *2.* Understand the population weighting mechanism in state-level hazardous heat calculations.
*3.* Evaluate the effectiveness of the author's methods compared to similar research.

# Study metadata

-   `Key words`: Comma-separated list of keywords (tags) for searchability. Geographers often use one or two keywords each for: theory, geographic context, and methods.
-   `Subject`: Social and Behavioral Sciences: Geography: Geographic Information Sciences, Human Geography, Nature and Society Relations
-   `Date created`: 04/14/25
-   `Date modified`: 04/21/25
-   `Spatial Coverage`: United States Lower 48
-   `Spatial Resolution`: Carceral facility points and States
-   `Spatial Reference System`: Specify the geographic or projected coordinate system for the study, e.g. EPSG:4326
-   `Temporal Coverage`: 1982-2020
-   `Temporal Resolution`: 1 year

## Original study spatio-temporal metadata

-   `Spatial Coverage`: United States Lower 48
-   `Spatial Resolution`: Carceral facility points and States
-   `Spatial Reference System`: spatial reference system of original study
-   `Temporal Coverage`: 1982-2020
-   `Temporal Resolution`: 1 year

# Study design

This study is a **reproduction study**, and the original study is more **exploratory** in design.
The primary objective for exploration through research and analysis investigated in the original study was exposure to hazardous heat in carceral facilities in the continental U.S.
The authors wanted to examine how exposure to hazardous heat changed over time from 1982-2020, as well as how exposure within carceral facilities compared to exposure in the rest of the state.
In general, determining the spatial distribution of carceral facilities with higher levels of hazardous heat exposure was also an objective of the original paper

# Materials and procedure

## Computational environment

```{r environment-setup, include = FALSE}
# record all the packages you are using here
# this includes any calls to library(), require(),
# and double colons such as here::i_am()
packages <- c("tidyverse", "here")

# force all conflicts to become errors
# if you load dplyr and use filter(), R has to guess whether you mean dplyr::filter() or stats::filter()
# the conflicted package forces you to be explicit about this
# disable at your own peril
# https://conflicted.r-lib.org/
require(conflicted)

# load and install required packages
# https://groundhogr.com/
if (!require(groundhog)) {
  install.packages("groundhog")
  require(groundhog)
}

# this date will be used to determine the versions of R and your packages
# it is best practice to keep R and its packages up to date
groundhog.day <- "2023-06-26"

# this replaces any library() or require() calls
groundhog.library(packages, groundhog.day)
# you may need to install a correct version of R
# you may need to respond OK in the console to permit groundhog to install packages
# you may need to restart R and rerun this code to load installed packages
# In RStudio, restart r with Session -> Restart Session

# record the R processing environment
# alternatively, use devtools::session_info() for better results
writeLines(
  capture.output(sessionInfo()),
  here("procedure", "environment", paste0("r-environment-", Sys.Date(), ".txt"))
)

# save package citations
knitr::write_bib(c(packages, "base"), file = here("software.bib"))

# set up default knitr parameters
# https://yihui.org/knitr/options/
knitr::opts_chunk$set(
  echo = FALSE, # Show outputs, but not code. Change to TRUE to show code as well
  fig.retina = 4,
  fig.width = 8,
  fig.path = paste0(here("results", "figures"), "/")
)
```

## Data and variables

Describe the **data sources** and **variables** to be used.
Data sources may include plans for observing and recording **primary data** or descriptions of **secondary data**.
For secondary data sources with numerous variables, the analysis plan authors may focus on documenting only the variables intended for use in the study.

Primary data sources for the study are to include ...
. Secondary data sources for the study are to include ...
.

Each of the next subsections describes one data source.

### Primary data source1 name

-   `Title`: Title of data source
-   `Abstract`: Brief description of the data source
-   `Spatial Coverage`: Specify the geographic extent of your study. This may be a place name and link to a feature in a gazetteer like GeoNames or OpenStreetMap, or a well known text (WKT) representation of a bounding box.
-   `Spatial Resolution`: Specify the spatial resolution as a scale factor, description of the level of detail of each unit of observation (including administrative level of administrative areas), and/or or distance of a raster GRID size
-   `Spatial Representation Type`: Specify the model of spatial data representation, e.g. one of `vector`, `grid`, `textTable`, `tin` (triangulated irregular network), etc. If the type is `vector`, also specify the geometry type as in the OGC Simple Feature Access standard (<https://www.ogc.org/publications/standard/sfa/>) , e.g. `POINT`, `LINESTRING`, `MULTIPOLYGON`, etc.
-   `Spatial Reference System`: Specify the geographic or projected coordinate system for the study
-   `Temporal Coverage`: Specify the temporal extent of your study---i.e. the range of time represented by the data observations.
-   `Temporal Resolution`: Specify the temporal resolution of your study---i.e. the duration of time for which each observation represents or the revisit period for repeated observations
-   `Lineage`: Describe and/or cite data sources and/or methodological steps planned to create this data source.
    -   sampling scheme, including spatial sampling
    -   target sample size and method for determining sample size
    -   stopping criteria for data collection and sampling (e.g. sample size, time elapsed)
    -   de-identification / anonymization
    -   experimental manipulation
-   `Distribution`: Describe who will make the data available and how?
-   `Constraints`: Legal constraints for *access* or *use* to protect *privacy* or *intellectual property rights*
-   `Data Quality`: State any planned quality assessment
-   `Variables`: For each variable, enter the following information. If you have two or more variables per data source, you may want to present this information in table form (shown below)
    -   `Label`: variable name as used in the data or code
    -   `Alias`: intuitive natural language name
    -   `Definition`: Short description or definition of the variable. Include measurement units in description.
    -   `Type`: data type, e.g. character string, integer, real
    -   `Accuracy`: e.g. uncertainty of measurements
    -   `Domain`: Expected range of Maximum and Minimum of numerical data, or codes or categories of nominal data, or reference to a standard codebook
    -   `Missing Data Value(s)`: Values used to represent missing data and frequency of missing data observations
    -   `Missing Data Frequency`: Frequency of missing data observations: not yet known for data to be collected

| Label | Alias | Definition | Type | Accuracy | Domain | Missing Data Value(s) | Missing Data Frequency |
|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|
| variable1 | ... | ... | ... | ... | ... | ... | ... |
| variable2 | ... | ... | ... | ... | ... | ... | ... |

### Primary data source2 name

...
same form as above...\
Metadata documents in the markdown `.md` format can be included directly with the `includeMarkdown()` function.
This requires the `markdown` package.

### Secondary data source1 name

-   `Title`: Title of data source
-   `Abstract`: Brief description of the data source
-   `Spatial Coverage`: Specify the geographic extent of your study. This may be a place name and link to a feature in a gazetteer like GeoNames or OpenStreetMap, or a well known text (WKT) representation of a bounding box.
-   `Spatial Resolution`: Specify the spatial resolution as a scale factor, description of the level of detail of each unit of observation (including administrative level of administrative areas), and/or or distance of a raster GRID size
-   `Spatial Reference System`: Specify the geographic or projected coordinate system for the study
-   `Temporal Coverage`: Specify the temporal extent of your study---i.e. the range of time represented by the data observations.
-   `Temporal Resolution`: Specify the temporal resolution of your study---i.e. the duration of time for which each observation represents or the revisit period for repeated observations
-   `Lineage`: Describe and/or cite data sources and/or methodological steps used to create this data source
-   `Distribution`: Describe how the data is distributed, including any persistent identifier (e.g. DOI) or URL for data access
-   `Constraints`: Legal constraints for *access* or *use* to protect *privacy* or *intellectual property rights*
-   `Data Quality`: State result of quality assessment or state "Quality unknown"
-   `Variables`: For each variable, enter the following information. If you have two or more variables per data source, you may want to present this information in table form (shown below)
    -   `Label`: variable name as used in the data or code
    -   `Alias`: intuitive natural language name
    -   `Definition`: Short description or definition of the variable. Include measurement units in description.
    -   `Type`: data type, e.g. character string, integer, real
    -   `Accuracy`: e.g. uncertainty of measurements
    -   `Domain`: Range (Maximum and Minimum) of numerical data, or codes or categories of nominal data, or reference to a standard codebook
    -   `Missing Data Value(s)`: Values used to represent missing data and frequency of missing data observations
    -   `Missing Data Frequency`: Frequency of missing data observations

| Label | Alias | Definition | Type | Accuracy | Domain | Missing Data Value(s) | Missing Data Frequency |
|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|
| variable1 | ... | ... | ... | ... | ... | ... | ... |
| variable2 | ... | ... | ... | ... | ... | ... | ... |

### Secondary data source2 name

...
same form as above...

## Prior observations

We have the derived data to work off of, we have neither visualized or analyzed prison data or WBGTmax temperature data before.

At the time of this study pre-registration, the authors had \_\_\_\_\_ prior knowledge of the geography of the study region with regards to the \_\_\_\_ phenomena to be studied.
This study is related to \_\_\_\_ prior studies by the authors

For each primary data source, declare the extent to which authors had already engaged with the data:

-   [ ] no data collection has started
-   [ ] pilot test data has been collected
-   [ ] data collection is in progress and data has not been observed
-   [ ] data collection is in progress and \_\_% of data has been observed
-   [ ] data collection is complete and data has been observed. Explain how authors have already manipulated / explored the data.

For each secondary source, declare the extent to which authors had already engaged with the data:

-   [ ] data is not available yet
-   [ ] data is available, but only metadata has been observed
-   [ ] metadata and descriptive statistics have been observed
-   [ ] metadata and a pilot test subset or sample of the full dataset have been observed
-   [ ] the full dataset has been observed. Explain how authors have already manipulated / explored the data.

If pilot test data has been collected or acquired, describe how the researchers observed and analyzed the pilot test, and the extent to which the pilot test influenced the research design.

## Bias and threats to validity

Given the research design and primary data to be collected and/or secondary data to be used, discuss common threats to validity and the approach to mitigating those threats, with an emphasis on geographic threats to validity.

These include: - uneven primary data collection due to geographic inaccessibility or other constraints - multiple hypothesis testing - edge or boundary effects - the modifiable areal unit problem - nonstationarity - spatial dependence or autocorrelation - temporal dependence or autocorrelation - spatial scale dependency - spatial anisotropies - confusion of spatial and a-spatial causation - ecological fallacy - uncertainty e.g. from spatial disaggregation, anonymization, differential privacy

## Data transformations

Planned deviation: we will not attempt x because the data is .... therefore we will skip to ...

Describe data transformations conducted by the authors that are not feasible for reproduction. 

Explain what we believe the authors did for WBGTmax grid - document as data source we do not have access to, and its lineage

Give readers a sense of the workflow that we are not doing/unable to do

### Reproduce Fig. 1

#### Step 1: Join author-provided WBGTmax by day grid data to author-provided carceral facility point data

Use `st_join()`

*Result:* Rds table of WBGTmax by day by prison

#### Step 2: Filter result by days when WBGTmax exceeded 28 degrees C

#### Step 3: Group by carceral facility type and year

Count to produce summary of days exceeded per year by facility

*Result:* Rds table with variables\
- prison facility - facility type - prison population - n days exceeding 28 degrees - year

#### Step 4: Create Fig. 1a and b using results

### Reproduce Fig. 2

#### Step 1: Begin with result from Step 3 from reproduction of Fig. 1

#### Step 2: Spatial join county population by year data

*Result:* Rds table with variables\
- prison facility - facility type - prison population - county - population - n days exceeding 28 degrees - year

#### Step 3: Population-weighted aggregation

Aggregate data into states

weighted sum of days exceeded across all counties of the state

sum of days exceeded multiplied by (Ratio of county population / state population)

#### Step 4: Create Fig. 2a, b and c using results

## Planned deviation for reproduction: Investigating temperature threshold

Repeat workflow for reproducing figures 1 and 2, instead filtering for days when WBGTmax exceeded 29.4 degrees C (85 degrees F standard informed by other literature)

## Planned deviation for reproduction: Investigating sources of uncertainy/error/bias

### How many open facilities had a population of -999? (Potential source of uncertainy)

#### Step 1: Select facilities with population of -999 from author-provided carceral facilities data.

Report number of facilities compared to authors' number.

#### Step 2: Map result.

## Analysis

If anything - Fig 2c - comparison of prisons to state

# Results

Move steps that create maps and graphs into results

Present figures (reproduced from original study and planned deviations).

# Discussion

what are the implications of us being able to recreate or not recreate the figures? why does it matter for this to be reproducible

mention groundhog usage for sustainable reproduction

Describe how the results are to be interpreted *vis a vis* each hypothesis or research question.
Research that maximum daily doesn't matter as much for heat stress - long stretches of nighttime lows are more serious

# Integrity Statement

This is the first version of our pre-analysis plan

Include an integrity statement - The authors of this preregistration state that they completed this preregistration to the best of their knowledge and that no other preregistration exists pertaining to the same hypotheses and research.
If a prior registration *does* exist, explain the rationale for revising the registration here.

# Acknowledgements

This report is based upon the template for Reproducible and Replicable Research in Human-Environment and Geographical Sciences, [DOI:[10.17605/OSF.IO/W29MQ](DOI:%5B10.17605/OSF.IO/W29MQ){.uri}](https://doi.org/10.17605/OSF.IO/W29MQ)

## References

> Kedron, P., & Holler, J.
> (2023).
> Template for Reproducible and Replicable Research in Human-Environment and Geographical Sciences.
> <https://doi.org/10.17605/OSF.IO/W29MQ>
